-- Table: public.catalogo_alergias

-- DROP TABLE IF EXISTS public.catalogo_alergias;

CREATE TABLE IF NOT EXISTS public.catalogo_alergias
(
    allergen_code bigint,
    allergy_category_code bigint,
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    allergen_fsn text COLLATE pg_catalog."default",
    allergy_category_fsn text COLLATE pg_catalog."default",
    preferred_term_en character varying(255) COLLATE pg_catalog."default",
    preferred_term_pt character varying(255) COLLATE pg_catalog."default",
    synonym_1 character varying(255) COLLATE pg_catalog."default",
    synonym_2 character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT catalogo_alergias_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.catalogo_alergias
    OWNER to postgres;