
app.datasource.sqlite.url=jdbc:sqlite:allergy_catalog.db
app.datasource.sqlite.driver-class-name=org.sqlite.JDBC

app.jpa.sqlite.hibernate.ddl-auto=update
app.jpa.sqlite.show-sql=true
app.jpa.sqlite.properties.hibernate.format_sql=true
app.jpa.sqlite.properties.hibernate.dialect=org.hibernate.community.dialect.SQLiteDialect

app.datasource.pg.url=jdbc:postgresql://localhost:5432/allergy_logs
app.datasource.pg.username=postgres
app.datasource.pg.password=${PW_POSTGRES}
app.datasource.pg.driver-class-name=org.postgresql.Driver

app.jpa.pg.hibernate.ddl-auto=create
app.jpa.pg.show-sql=true
app.jpa.pg.properties.hibernate.format_sql=false
app.jpa.pg.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.application.name=Allergy
app.csv.file.path=classpath:db/catalogo_alergias.csv